### ISSUE TITLE
Update in the future

### ISSUE THREAD

**Issue by fr500** [libretro/libretro-meta#21]
_From @sergiobenrocha2 on October 5, 2016 22:39_

Just a reminder to me or anyone in the future: 

Do a "git reset HEAD^ --hard" until def5a46 first

I merged the stable branch btw

_Copied from original issue: libretro/mgba#44_

**Comment by fr500** [comment]
_From @sergiobenrocha2 on January 4, 2017 21:47_

upstream master branch: https://github.com/sergiobenrocha2/mgba/commits/master

**Comment by sergiobenrocha2** [comment]
My repo is up to dated with upstream, I can build, but I get this while running:

Edit: missing  -D_GNU_SOURCE -DHAVE_LOCALE, it's working now

```
Starting program: /usr/bin/retroarch -L mgba_libretro.so /home/sergio/Games/ROMs/Game\ Boy\ Advance/Advance\ Wars\ \(USA\)\ \(Rev\ 1\).zip
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffecaea700 (LWP 19588)]

Program received signal SIGSEGV, Segmentation fault.
__strncmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
209	../sysdeps/x86_64/multiarch/../strcmp.S: No such file or directory.
(gdb) 
(gdb) 
(gdb) bt full
#0  __strncmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
No locals.
#1  0x00007fffec0a80ff in HashTableLookup (table=0x555555a88878, key=0x7fffec0a9dd8 "logLevel") at src/util/table.c:177
        hash = 282882130
        list = 0x555555a8a9a0
        entry = 2
        i = 0
#2  0x00007fffec0a5792 in ConfigurationGetValue (configuration=0x555555a88858, section=0x0, key=0x7fffec0a9dd8 "logLevel") at src/util/configuration.c:148
        currentSection = 0x555555a88878
#3  0x00007fffec04600a in _lookupValue (config=0x555555a88818, key=0x7fffec0a9dd8 "logLevel") at src/core/config.c:67
        value = 0x0
#4  0x00007fffec0460ab in _lookupIntValue (config=0x555555a88818, key=0x7fffec0a9dd8 "logLevel", out=0x555555a888ec) at src/core/config.c:83
        charValue = 0x7fffffff84d0 "\030\210\250UUU"
        end = 0x555555a88818 "\200\267\253UUU"
        value = 0
#5  0x00007fffec0466f9 in mCoreConfigMap (config=0x555555a88818, opts=0x555555a888e0) at src/core/config.c:327
        audioBuffers = 1437108312
        fakeBool = 21845
#6  0x00007fffec04707b in mCoreLoadForeignConfig (core=0x555555a88800, config=0x555555a88818) at src/core/core.c:227
No locals.
#7  0x00007fffec04704f in mCoreLoadConfig (core=0x555555a88800) at src/core/core.c:223
No locals.
#8  0x00007fffec0a1824 in _reloadSettings () at src/platform/libretro/libretro.c:100
        opts = {bios = 0x0, skipBios = false, useBios = true, logLevel = 0, frameskip = 0, rewindEnable = false, rewindBufferCapacity = 0, rewindSave = false, fpsTarget = 0, audioBuffers = 0, sampleRate = 0, fullscreen = 0, 
          width = 0, height = 0, lockAspectRatio = false, resampleVideo = false, suspendScreensaver = false, shader = 0x0, savegamePath = 0x0, savestatePath = 0x0, screenshotPath = 0x0, patchPath = 0x0, volume = 256, 
          mute = false, videoSync = false, audioSync = false}
        var = {key = 0x7fffec0b3110 "mgba_idle_optimization", value = 0x555555abad40 "Remove Known"}
#9  0x00007fffec0a2a94 in retro_load_game (game=0x555555ab9bb0) at src/platform/libretro/libretro.c:480
        rom = 0x555555a88040
        save = 0x555555abd030
#10 0x0000555555592a39 in core_load_game (load_info=load_info@entry=0x7fffffff9710) at core_impl.c:293
        contentless = false
        is_inited = false
#11 0x00005555555a7ef9 in content_file_load (info=info@entry=0x555555ab9bb0, content=content@entry=0x555555abb270, content_ctx=content_ctx@entry=0x7fffffffbfc0, error_string=error_string@entry=0x7fffffffbf90, special=0x0)
    at tasks/task_content.c:583
        i = <optimized out>
        load_info = {info = 0x555555ab9bb0, content = 0x555555abb270, special = 0x0}
        msg = '\000' <repeats 632 times>...
        additional_path_allocs = 0x555555abb4a0
#12 0x00005555555a9a31 in content_file_init (error_string=0x7fffffffbf90, content_ctx=0x7fffffffbfc0) at tasks/task_content.c:764
        i = <optimized out>
        info = 0x555555ab9bb0
        content = 0x555555abb270
        ret = true
        special = <optimized out>
#13 content_init () at tasks/task_content.c:1655
        content_ctx = {subsystem = {data = 0x0, size = 0}, valid_extensions = 0x555555abb250 "gba|gb|gbc", directory_cache = 0x555555abb230 "/tmp", directory_system = 0x555555abb200 "/home/sergio/Games/RetroArch/system", 
          history_list_enable = true, block_extract = false, need_fullpath = false, set_supports_no_game_enable = true, patch_is_blocked = false, bios_is_missing = 85, check_firmware_before_loading = true, 
          temporary_content = 0x555555abafd0}
        ret = true
        error_string = 0x0
        sys_info = 0x555555a332c0 <runloop_system>
        settings = <optimized out>
#14 0x000055555559b2b7 in event_init_content () at command.c:1348
        contentless = false
        is_inited = false
#15 command_event_init_core (data=0x555555a1add0 <current_core_type>) at command.c:1406
        info = {env = 0x5555555da800 <rarch_environment_cb>}
        settings = 0x7fffecaeb010
#16 command_event (cmd=cmd@entry=CMD_EVENT_CORE_INIT, data=data@entry=0x555555a1add0 <current_core_type>) at command.c:2264
        boolean = false
#17 0x00005555555954e3 in retroarch_main_init (argc=4, argv=argv@entry=0x7fffffffde08) at retroarch.c:1078
        init_failed = false
#18 0x00005555555a6de3 in content_load (info=0x7fffffffc910) at tasks/task_content.c:280
        i = <optimized out>
        retval = true
        rarch_argc = 0
        rarch_argv_ptr = 0x7fffffffde08
        rarch_argv = {0x0 <repeats 32 times>}
        argv_copy = {0x0 <repeats 32 times>}
        rarch_argc_ptr = 0x7fffffffdce0
        wrap_args = 0x555555a86910
#19 task_load_content (content_info=content_info@entry=0x7fffffffdce0, launched_from_menu=launched_from_menu@entry=true, launched_from_cli=launched_from_cli@entry=true, error_string=error_string@entry=0x7fffffffdc60, 
    content_ctx=0x7fffffffdc70) at tasks/task_content.c:837
        name = "\000\311\377\377\377\177\000\000\000\000\000\223\377\377\377\377\070M\275\364\377\177\000\000\325|\336\367\377\177\000\000\001\000\000\000\377\177\000\000\b*\343\367\377\177\000\000\000\312\377\377\377\177\000\000\000\000`\223\377\377\377\377(M\275\364\377\177\000\000\325|\336\367\377\177\000\000\001\000\000\000\377\177\000\000\000%\343\367\377\177\000\000\060\312\377\377\377\177\000\000\000\000\300\223\377\377\377\377\030M\275\364\377\177\000\000\325|\336\367\377\177\000\000\001\000\000\000\377\177\000\000\000 \343\367\377\177\000\000`\312\377\377\377\177\000\000\000\000 \224\377\377\377\377\370L\275\364\377\177\000\000\325|\336\367\377\177\000\000\001\000\000\000\000\000\000\000\370:\343\367\377\177\000\000\220\312\377\377\377\177\000\000\000\000\000\000"...
        msg = "\000L\275\364\377\177\000\000H\000\000\000\000\000\000\000a4\000\000\000\200\377\377(\000\000\000\000\000\000\000Q4\000\000\000\200\377\377\003", '\000' <repeats 15 times>, "\060\000\000\000\000\000\000\000\260\313\377\377\377\177", '\000' <repeats 14 times>, "[", '\000' <repeats 19 times>, "n\000\000\000w", '\000' <repeats 11 times>, "\257\313\377\377\377\177\000\000|\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000|\000\000\000\377\177\000\000\000\360\342\367\377\177\000\000\350\071\374\367\377\177\000\000\000@\374\367\377\177\000\000\020E\374\367\377\177\000\000`Ǖ\362\377\177\000\000\200\347\001\000\000\000\000\000`"...
        contentless = false
        is_inited = false
#20 0x00005555555a90d2 in task_load_content_callback (loading_from_menu=true, loading_from_cli=true, content_info=0x7fffffffdce0) at tasks/task_content.c:1397
        content_ctx = {subsystem = {data = 0x0, size = 0}, valid_extensions = 0x0, directory_cache = 0x0, directory_system = 0x0, history_list_enable = false, block_extract = false, need_fullpath = false, 
          set_supports_no_game_enable = false, patch_is_blocked = false, bios_is_missing = false, check_firmware_before_loading = false, temporary_content = 0x5b00000000}
        ret = false
        error_string = 0x0
        settings = <optimized out>
#21 task_push_load_content_from_cli (core_path=<optimized out>, fullpath=<optimized out>, content_info=0x7fffffffdce0, type=<optimized out>, cb=<optimized out>, user_data=<optimized out>) at tasks/task_content.c:1454
No locals.
#22 0x0000555555591bb9 in rarch_main (argc=4, argv=0x7fffffffde08, data=0x0) at frontend/frontend.c:113
        info = {argc = 4, argv = 0x7fffffffde08, args = 0x0, environ_get = 0x555555590b10 <frontend_linux_get_env>}
        args = 0x0
#23 0x00007ffff25bff45 in __libc_start_main (main=0x55555558ef10 <main>, argc=4, argv=0x7fffffffde08, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffddf8) at libc-start.c:287
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -4940550743075848930, 93824992472855, 140737488346624, 0, 0, 4940550744191008030, 4940527893816147230}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7fffffffde30, 
              0x7ffff7ffe1c8}, data = {prev = 0x0, cleanup = 0x0, canceltype = -8656}}}
        not_first_call = <optimized out>
#24 0x000055555558ef40 in _start ()
No symbol table info available.
```

**Comment by sergiobenrocha2** [comment]
Getting the same with 0.5.2 too, missing -D_GNU_SOURCE -DHAVE_LOCALE on linux build

```
Starting program: /usr/bin/retroarch -L mgba_libretro.so /home/sergio/Games/ROMs/Game\ Boy\ Advance/Advance\ Wars\ \(USA\)\ \(Rev\ 1\).zip
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffecaea700 (LWP 31056)]

Program received signal SIGSEGV, Segmentation fault.
__strncmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
209	../sysdeps/x86_64/multiarch/../strcmp.S: No such file or directory.
(gdb) 
(gdb) 
(gdb) 
(gdb) bt full
#0  __strncmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
No locals.
#1  0x00007fffec0a466c in HashTableLookup (table=0x555555a88860, key=0x7fffec0a9665 "logLevel") at src/util/table.c:162
        hash = 282882130
        list = 0x555555a8b030
        entry = 2
        i = 0
#2  0x00007fffec0a6771 in ConfigurationGetValue (configuration=0x555555a88848, section=0x0, key=0x7fffec0a9665 "logLevel") at src/util/configuration.c:138
        currentSection = 0x555555a88860
#3  0x00007fffec04377e in _lookupValue (config=0x555555a88818, key=0x7fffec0a9665 "logLevel") at src/core/config.c:60
        value = 0x0
#4  0x00007fffec04381f in _lookupIntValue (config=0x555555a88818, key=0x7fffec0a9665 "logLevel", out=0x555555a888bc) at src/core/config.c:76
        charValue = 0x7fffffff84e0 "\030\210\250UUU"
        end = 0x555555a88818 ""
        value = 0
#5  0x00007fffec043e14 in mCoreConfigMap (config=0x555555a88818, opts=0x555555a888b0) at src/core/config.c:312
        audioBuffers = 1437108296
        fakeBool = 21845
#6  0x00007fffec04462e in mCoreLoadForeignConfig (core=0x555555a88800, config=0x555555a88818) at src/core/core.c:226
No locals.
#7  0x00007fffec044602 in mCoreLoadConfig (core=0x555555a88800) at src/core/core.c:222
No locals.
#8  0x00007fffec0a12ec in _reloadSettings () at src/platform/libretro/libretro.c:100
        opts = {bios = 0x0, skipBios = false, useBios = true, logLevel = 0, frameskip = 0, rewindEnable = false, rewindBufferCapacity = 0, fpsTarget = 0, audioBuffers = 0, 
          sampleRate = 0, fullscreen = 0, width = 0, height = 0, lockAspectRatio = false, resampleVideo = false, suspendScreensaver = false, shader = 0x0, savegamePath = 0x0, 
          savestatePath = 0x0, screenshotPath = 0x0, patchPath = 0x0, volume = 256, mute = false, videoSync = false, audioSync = false}
        var = {key = 0x7fffec0b3bb8 "mgba_idle_optimization", value = 0x555555abacc0 "Remove Known"}
#9  0x00007fffec0a255c in retro_load_game (game=0x555555ab9b30) at src/platform/libretro/libretro.c:480
        rom = 0x555555a88040
        save = 0x555555a880b0
#10 0x0000555555592a39 in core_load_game (load_info=load_info@entry=0x7fffffff9710) at core_impl.c:293
        contentless = false
        is_inited = false
#11 0x00005555555a7ef9 in content_file_load (info=info@entry=0x555555ab9b30, content=content@entry=0x555555abb1f0, content_ctx=content_ctx@entry=0x7fffffffbfc0, 
    error_string=error_string@entry=0x7fffffffbf90, special=0x0) at tasks/task_content.c:583
        i = <optimized out>
        load_info = {info = 0x555555ab9b30, content = 0x555555abb1f0, special = 0x0}
        msg = '\000' <repeats 632 times>...
        additional_path_allocs = 0x555555abb420
#12 0x00005555555a9a31 in content_file_init (error_string=0x7fffffffbf90, content_ctx=0x7fffffffbfc0) at tasks/task_content.c:764
        i = <optimized out>
        info = 0x555555ab9b30
        content = 0x555555abb1f0
        ret = true
        special = <optimized out>
#13 content_init () at tasks/task_content.c:1655
        content_ctx = {subsystem = {data = 0x0, size = 0}, valid_extensions = 0x555555abb1d0 "gba|gb|gbc", directory_cache = 0x555555abb1b0 "/tmp", 
          directory_system = 0x555555abb180 "/home/sergio/Games/RetroArch/system", history_list_enable = true, block_extract = false, need_fullpath = false, 
          set_supports_no_game_enable = true, patch_is_blocked = false, bios_is_missing = 85, check_firmware_before_loading = true, temporary_content = 0x555555abaf50}
        ret = true
        error_string = 0x0
        sys_info = 0x555555a332c0 <runloop_system>
        settings = <optimized out>
#14 0x000055555559b2b7 in event_init_content () at command.c:1348
        contentless = false
        is_inited = false
#15 command_event_init_core (data=0x555555a1add0 <current_core_type>) at command.c:1406
        info = {env = 0x5555555da800 <rarch_environment_cb>}
        settings = 0x7fffecaeb010
#16 command_event (cmd=cmd@entry=CMD_EVENT_CORE_INIT, data=data@entry=0x555555a1add0 <current_core_type>) at command.c:2264
        boolean = false
#17 0x00005555555954e3 in retroarch_main_init (argc=4, argv=argv@entry=0x7fffffffde08) at retroarch.c:1078
        init_failed = false
#18 0x00005555555a6de3 in content_load (info=0x7fffffffc910) at tasks/task_content.c:280
        i = <optimized out>
        retval = true
        rarch_argc = 0
        rarch_argv_ptr = 0x7fffffffde08
        rarch_argv = {0x0 <repeats 32 times>}
        argv_copy = {0x0 <repeats 32 times>}
        rarch_argc_ptr = 0x7fffffffdce0
        wrap_args = 0x555555a86910
#19 task_load_content (content_info=content_info@entry=0x7fffffffdce0, launched_from_menu=launched_from_menu@entry=true, launched_from_cli=launched_from_cli@entry=true, 
    error_string=error_string@entry=0x7fffffffdc60, content_ctx=0x7fffffffdc70) at tasks/task_content.c:837
        name = "\000\311\377\377\377\177\000\000\000\000\000\223\377\377\377\377\070M\275\364\377\177\000\000\325|\336\367\377\177\000\000\001\000\000\000\377\177\000\000\b*\343\367\377\177\000\000\000\312\377\377\377\177\000\000\000\000`\223\377\377\377\377(M\275\364\377\177\000\000\325|\336\367\377\177\000\000\001\000\000\000\377\177\000\000\000%\343\367\377\177\000\000\060\312\377\377\377\177\000\000\000\000\300\223\377\377\377\377\030M\275\364\377\177\000\000\325|\336\367\377\177\000\000\001\000\000\000\377\177\000\000\000 \343\367\377\177\000\000`\312\377\377\377\177\000\000\000\000 \224\377\377\377\377\370L\275\364\377\177\000\000\325|\336\367\377\177\000\000\001\000\000\000\000\000\000\000\370:\343\367\377\177\000\000\220\312\377\377\377\177\000\000\000\000\000\000"...
        msg = "\000L\275\364\377\177\000\000H\000\000\000\000\000\000\000a4\000\000\000\200\377\377(\000\000\000\000\000\000\000Q4\000\000\000\200\377\377\003", '\000' <repeats 15 times>, "\060\000\000\000\000\000\000\000\260\313\377\377\377\177", '\000' <repeats 14 times>, "[", '\000' <repeats 19 times>, "n\000\000\000w", '\000' <repeats 11 times>, "\257\313\377\377\377\177\000\000|\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000|\000\000\000\377\177\000\000\000\360\342\367\377\177\000\000\350\071\374\367\377\177\000\000\000@\374\367\377\177\000\000\020E\374\367\377\177\000\000`Ǖ\362\377\177\000\000\200\347\001\000\000\000\000\000`"...
        contentless = false
        is_inited = false
#20 0x00005555555a90d2 in task_load_content_callback (loading_from_menu=true, loading_from_cli=true, content_info=0x7fffffffdce0) at tasks/task_content.c:1397
        content_ctx = {subsystem = {data = 0x0, size = 0}, valid_extensions = 0x0, directory_cache = 0x0, directory_system = 0x0, history_list_enable = false, 
          block_extract = false, need_fullpath = false, set_supports_no_game_enable = false, patch_is_blocked = false, bios_is_missing = false, 
          check_firmware_before_loading = false, temporary_content = 0x5b00000000}
        ret = false
        error_string = 0x0
        settings = <optimized out>
#21 task_push_load_content_from_cli (core_path=<optimized out>, fullpath=<optimized out>, content_info=0x7fffffffdce0, type=<optimized out>, cb=<optimized out>, 
    user_data=<optimized out>) at tasks/task_content.c:1454
No locals.
#22 0x0000555555591bb9 in rarch_main (argc=4, argv=0x7fffffffde08, data=0x0) at frontend/frontend.c:113
        info = {argc = 4, argv = 0x7fffffffde08, args = 0x0, environ_get = 0x555555590b10 <frontend_linux_get_env>}
        args = 0x0
#23 0x00007ffff25bff45 in __libc_start_main (main=0x55555558ef10 <main>, argc=4, argv=0x7fffffffde08, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffddf8) at libc-start.c:287
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -3328279860204000733, 93824992472855, 140737488346624, 0, 0, 3328279861219568163, 3328291714347444771}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7fffffffde30, 0x7ffff7ffe1c8}, data = {prev = 0x0, cleanup = 0x0, canceltype = -8656}}}
        not_first_call = <optimized out>
#24 0x000055555558ef40 in _start ()
No symbol table info available.
```
